apiVersion: argoproj.io/v1alpha1  
kind: AppProject
metadata:
  name: financeproject
  namespace: argocd
spec:
  description: Finance Project
  sourceRepos:
    - "https://github.com/venkatamamidibathula/guestbookprivaterepo.git"
  destinations:
    - namespace: 'finance'
      server: 'https://kubernetes.default.svc'  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'